module HtmlTagVariables
	
	$html_tags = ["<!DOCTYPE html>",
				 "<html>", "</html>",
				 "<head>", "</head>",
				 "<title>", "</title>",
				 "<body>", "</body>",
				 "<h1>", "</h1>",
				 "<h2>", "</h2>",
				 "<h3>", "</h3>",
				 "<h4>", "</h4>",
				 "<h5>", "</h5>",
				 "<h6>", "</h6>",
				 "<p>", "</p>",
				 "<code>", "</code>", 
				 "<em>", "</em>", 
				 "<i>", "</i>", 
				 "<kbd>", "</kbd>", 
				 "<pre>", "</pre>", 
				 "<small>", "</small>", 
				 "<strong>", "</strong>", 
				 "<abbr>", "</abbr>", 
				 "<address>", "</address>", 
				 "<bdo>", "</bdo>", 
				 "<blockquote>", "</blockquote>", 
				 "<cite>", "</cite>", 
				 "<del>", "</del>", 
				 "<ins>", "</ins>", 
				 "<sub>", "</sub>", 
				 "<sup>", "</sup>", 
				 "<ul>", "</ul>", 
				 "<li>", "</li>", 
				 "<ol>", "</ol>", 
				 "<dl>", "</dl>", 
				 "<dt>", "</dt>", 
				 "<dd>", "</dd>", 
				 "<tr>", "</tr>", 
				 "<th>", "</th>", 
				 "<td>", "</td>", 
				 "<table border=", "</table>", 
				 "<div>", "</div>",
				 "<style type", "</style>", 
				 "<a id=", 
				 "<span>", "</span>", 
				 "<form", "</form>",
				 "<input type=", 
				 "<iframe ", "</iframe>",
				 "<select>", "</select>", 
				 "<option>", "</option>", 
				 "<option selected=",
				 "<textarea ", "</textarea>", 
				 "&lt;", "&gt;", "&#169;"
]

end